config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"

  get "terms", to: "terms#show"
  get "about", to: "about#show"
  resource :contacts, only: %i[new create], path_names: {new: ""}
  resources :articles do
    resources :comments, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :text, presence: true
  validates_length_of :title, maximum: 140
  validates_length_of :text, maximum: 4000

  has_one_attached :thumbnail
  has_rich_text :text

  has_many :comments, dependent: :destroy

  def subject
    title
  end

  def last_comment
    comments.last
  end

  def thumbnail_edit
    thumbnail.variant(resize_to_limit: [250, 250]).processed
  end

  def thumbnail_index
    thumbnail.variant(resize_to_limit: [580, 330]).processed
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :author, :body, presence: true
  validates_length_of :body, maximum: 4000

  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email,
    :message,
    presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  def index
    @articles = Article.all.order("created_at DESC")
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create article_params
    if @article.valid?
      redirect_to @article, notice: "Article Created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update article_params
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :author, :content, :thumbnail)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.create(params.require(:contact).permit(:email, :message))
    if @contact.valid?
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  def show
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def owner?(object)
    current_user.nil? || current_user.username != @article.author
  end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/about/show.html.erb
<h3 class="text-center m-4">Page About</h3>

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>
  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_comments.html.erb
<div class="p-4 mb-3">
  <div class="mb-4">
    <h3>
      <small class="text-body-secondary">
        <%= pluralize(@article.comments.size, "Comment") %>
      </small>
    </h3>
  </div>
  <% @article.comments.order("created_at desc").each do |c|%>
    <div class="bg-dark-subtle mb-2 p-4">
      <figure >
        <blockquote class="blockquote">
          <p><%= c.body %></p>
        </blockquote>
        <figcaption class="blockquote-footer">
          <cite title="Source Title"><%= c.author %></cite>
        </figcaption>
      </figure>
    </div>
  <%end%>
</div>

app/views/articles/_form.html.erb
<div class="col-md-12">
  <%= form_with model: @article, data: { turbo: false} do |f| %>
    <% if @article.errors.any? %>
      <div class="alert alert-warning d-flex align-items-center justify-content-center" id="error_explanation" role="alert">
        <h5><%= pluralize(@article.errors.count, "error") %> prohibited this Message from being submited:</h5>
        <ul>
          <% @article.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="col-md-12">
      <div class="col-md-12 mb-3">
        <%= f.hidden_field :author, class: "form-control", placeholder: "Author", value: current_user.username %>
      </div>
      <div class="col-md-12 mb-3">
        <%= f.label :title, class: "form-label" %>
        <%= f.text_field :title, class: "form-control", placeholder: "Enter Title" %>
      </div>
      <%# File Input %>
      <div class="mb-3">
        <% if @article.thumbnail.attached? %>
          <%= image_tag @article.thumbnail_edit %>
        <% end %>
      </div>
      <div class="mb-3">
        <%= f.label :thumbnail, 'Select thumbnail image for Article', class: "form-label" %>
        <%= f.file_field :thumbnail, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :text, class: "form-label" %>
        <%= f.rich_text_area :text, class: "form-control" %>
      </div>
      <%= f.submit class: "btn btn-primary mb-4" %>
    <% end %>
  </div>
</div>

app/views/articles/_form_comments.html.erb
<div class="col-md-12 mt-4">
  <h3>Add Comment:</h3>
  <%= form_for([@article, Comment.new]) do |f| %>
    <div class="col-md-12 mt-4">
      <div class="col-md-12 mb-3">
        <%= f.hidden_field :author, class: "form-control", value: current_user.username if user_signed_in? %>
      </div>
      <div class="mb-3">
        <%= f.text_area :body, class: "form-control", rows: 5, maxlength: "1000", required: true %>
      </div>
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= f.submit class: "btn btn-primary mb-4", data: { turbo: false}%>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/create.html.erb
<h1 class="text-center m-4">Article Created</h1>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<% @articles.each do |a| %>
  <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
    <div class="row">
      <div class="col-lg-6">
        <h1 class="display-4 fst-italic"><%= a.title %></h1>
        <p class="lead my-3"><%= truncate(strip_tags(a.text.to_s), length: 125) %></p>
        <p class="lead mb-0"><%= link_to 'Continue reading...', article_path(a), class: "text-body-emphasis fw-bold" %></p>
      </div>
      <div class="col-lg-6">
        <%= image_tag a.thumbnail_index, class: "rounded float-end d-none d-sm-block" if a.thumbnail.present? %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<h3 class="text-center m-4"><%= t("new_article.create") %></h4>
<%= render 'form' %>

app/views/articles/show.html.erb
<article class="blog-post">
  <h2 class="display-5 link-body-emphasis mb-1"><%=@article.title%></h2>
  <p class="blog-post-meta"><%=@article.created_at.localtime.strftime('%d-%B-%Y %H:%M') %> by <a href=""><%=@article.author%></a></p>
  <div class="trix-content">
    <%= @article.text %>
  </div>
</article>
<% if owner?(@article) %>
<% else %>
  <%= link_to 'Edit', edit_article_path, class: "btn btn-primary" %>
  <%= link_to 'Delete', article_path(@article), class: "btn btn-primary", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
<% end %>
<%= render 'form_comments' %>
<%= render 'comments' %>

app/views/contacts/_form.html.erb
<div class="col-md-12">
  <%= form_with model: @contact, data: { turbo: false} do |f| %>
    <% if @contact.errors.any? %>
      <div class="alert alert-warning d-flex align-items-center justify-content-center" id="error_explanation" role="alert">
        <h5><%= pluralize(@contact.errors.count, "error") %> prohibited this Message from being submited:</h5>
        <ul>
          <% @contact.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="col-md-12">
      <div class="col-md-6 mb-3">
        <%= f.label :email, class: "form-label" %>
        <%= f.email_field :email, class: "form-control", placeholder: "name@example.com" %>
      </div>
      <div class="mb-3">
        <%= f.label :message, class: "form-label" %>
        <%= f.text_area :message, class: "form-control", rows: 3 %>
      </div>
      <%= f.submit "Submit", class: "btn btn-primary mb-4" %>
    <% end %>
  </div>
</div>

app/views/contacts/create.html.erb
<p>Thank you! Your message was sent.</p>

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-12">
    <figure>
    <h3 class="text-center m-4"><%= t("contacts.contact_us") %></h3>
      <blockquote class="blockquote">
        <p>Feel free to drop me a line or two, and remember, the funnier the better – my inbox thrives on side-splitting hilarity!</p>
      </blockquote>
      <figcaption class="blockquote-footer mt-2">
        Cheers, <cite title="Source Title">Vladimir Egorov</cite>
      </figcaption>
    </figure>
  </div>
  <div class="row mt-4">
    <%= render "form" %>
  </div>
</div>

app/views/home/index.html.erb
<div class="container-fluid">
  <div class="card mb-3" style="max-width: 100%">
    <div class="row g-0">
      <div class="col-md-6">
        <%= image_tag 'beach-1408077.jpg', class: "img-fluid rounded-start", alt: "..." %>
      </div>
      <div class="col-md-6">
        <div class="card-body">
          <h5 class="card-title">Hello!</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="py-2 bg-body-tertiary border-bottom mb-3">
  <div class="container d-flex flex-wrap">
    <div class="navbar w-100">
      <ul class="nav me-auto">
        <li class="nav-item">
          <a class="navbar-brand" href="<%= root_path %>">
            <%= image_tag 'BloxX1-logos_black.png', height: "35", class: "d-inline-block" %>
          </a>
        </li>
        <li class="nav-item">
          <a href="<%= new_article_path %>" class="nav-link link-body-emphasis px-2">New Article</a>
        </li>
      </ul>
      <div class="dropdown d-flex justify-content-end">
        <% if user_signed_in? %>
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-turbo-method="delete">Sign out</a>
            </li>
          </ul>
        <% else %>
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Hello?</a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="<%= new_user_session_path %>">Login</a>
            </li>
            <li>
              <a class="dropdown-item" href="<%= new_user_registration_path %>">Sign up</a>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>BloxX1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet"
                  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body class="bg-body d-flex flex-column min-vh-100">
    <%= render 'layouts/nav' %>
    <div class="container">
      <div>
        <% if notice.present? %>
          <p class="alert alert-primary" role="alert">
            <%= notice %>
          </p>
        <% end %>
        <% if alert.present? %>
          <p class="alert alert-warning" role="alert">
            <%= alert %>
          </p>
        <% end %>
      </div>
      <%= yield %>
    </div>
    <footer class="mt-auto bg-body-tertiary">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <ul class="nav justify-content-center">
              <li class="nav-item"><a href="<%=root_path%>" class="nav-link px-2 text-muted">Home</a></li>
              <li class="nav-item"><a href="<%=about_path%>" class="nav-link px-2 text-muted">About</a></li>
              <li class="nav-item"><a href="<%=terms_path%>" class="nav-link px-2 text-muted">Terms</a></li>
              <li class="nav-item"><a href="<%=new_contacts_path%>" class="nav-link px-2 text-muted">Contacts</a></li>
            </ul>
            <div class="nav justify-content-center">
              <small>&copy; <%= Time.now.year %> BloxX1. All rights reserved.</small>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/terms/show.html.erb
<h3 class="text-center m-4">My Hilarious Blog - Terms of Use</h3>